### ISSUE TITLE
Протестировать ветки и научиться мерджить

### ISSUE THREAD

**Issue by zakharovroman** [zakharovroman/Quiz#1]
Всем участникам научиться работать с ветками и мерджить. Ветку мастер не трогаем

**Comment by AnzhelikaP** [comment]
[questionsAnswers copy.pages.zip](https://github.com/zakharovroman/Quiz/files/4770180/questionsAnswers.copy.pages.zip)

**Comment by AnzhelikaP** [comment]
Хотела уменьшенную копию файла прикрепить

**Comment by zakharovroman** [comment]
Файлы где то нужно хранить для проекта. Обычно сторонние используются средства. Но лучше скорее всего в самом проекте
